# .github/ISSUE_TEMPLATE/01-topo-fixes.yml

name: "Map Error: Topo Fixes"
description: "Report topology fixes for map items." 
title: "[Map Error] <item-identifier> Topo Fixes"
labels:
  - map-error-topo-fixes
body:
  - type: markdown
    attributes:
      value: |
        The title should not be changed and will be automatically updated based on the Item Identifier.
        Thanks for reporting a map item error!
        Please provide the required details below.
        Use this map to identify the item: [Map](https://spatial.dev.water.noaa.gov/view/hydrofabric).
  - type: input
    id: item-identifier
    attributes:
      label: "Item Identifier"
      description: "The identifier of the item (e.g., wb-1455862)."
      placeholder: "wb-1455862"
    validations:
      required: true
  - type: input
    id: topology-toid
    attributes:
      label: "Topology toid"
      description: "The toid of the feature (e.g., wb-1455862)."
      placeholder: "wb-1455862"
    validations:
      required: true
  - type: input
    id: vpu
    attributes:
      label: "VPU"
      description: "The VPU where the issue occurs (e.g., 01)."
      placeholder: "01"
    validations:
      required: true
  - type: dropdown
    id: hf-version
    attributes:
      label: "Hydrofabric Version"
      description: "Select the type of hydrofabric version."
      options:
        - v2.2
        - other
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the issue"
      description: "Provide a summary of the issue. **Optional:** You can upload an image by dragging and dropping it into the issue description or by using the 'Attach files' feature below."
      placeholder: "E.g., the flowpath should drain to a water body with specific identifier..."
    validations:
      required: false