# .github/ISSUE_TEMPLATE/01-topo-fixes.yml

name: "Flowpaths: Topo Fixes"
description: "Report Flowpaths topology fixes for map items." 
title: "[Hydrofabric] Flowpaths <item-identifier> Topo Fixes"
labels:
  - Hydrofabric-topo-fixes
body:
  - type: markdown
    attributes:
      value: |
        The title should not be changed and will be automatically updated based on the Item Identifier.
        Thanks for reporting a hydrofabric issue!
        Please provide the required details below. 
        Please ensure your report includes the **corrected** topology of identifiers, not the erroneous one.
        All issues must be reported using reference fabric identifiers. If an issue originates in a refactored or NextGen hydrofabric, please trace it back to the reference fabric before submitting. Use the [Hydrofabric Viewer Map](https://hydrofabric.lynker-spatial.com/) for assistance.
  - type: dropdown
    id: hf-version
    attributes:
      label: "Hydrofabric Version"
      description: "Select the type of hydrofabric version."
      options:
        - v2.2
        - v2.3
    validations:
      required: true  
  - type: dropdown
    id: report-mode
    attributes:
      label: "Report Mode"
      description: "Select if you are reporting a single instance or multiple instances."
      options:
        - "Report a single instance"
        - "Report many instances (simply paste columns of data)"
    validations:
      required: true
  - type: textarea 
    id: vpu
    attributes:
      label: "VPU(s)" 
      description: | 
        The VPU(s) where the issue(s) occur (e.g., 01).
        If 'Report many instances' is selected, paste one VPU per line (copy and paste column as plain text without header), corresponding to each Item Identifier.
        Ensure the number of lines matches the Item Identifiers. 
      placeholder: |
        01
        02
        01
      render: shell
    validations:
      required: true
  - type: textarea
    id: item-identifier
    attributes:
      label: "Item Identifier(s)"
      description: |
        The identifier(s) of the item(s) (e.g., 1455862).
        If 'Report many instances' is selected, paste one identifier per line (copy and paste column as plain text without header). Each line will become a separate entry in the CSV.
      placeholder: |
        1455862
        1455863
        1455864
      render: shell
    validations:
      required: true
  - type: textarea
    id: topology-toid
    attributes:
      label: "Topology toid(s)"
      description: |
        The toid(s) of the feature(s) (e.g., 1455862).
        If 'Report many instances' is selected, paste one toid per line (copy and paste column as plain text without header), corresponding to each Item Identifier.
        Ensure the number of lines matches the Item Identifiers.
      placeholder: |
        1455862
        1455863
        1455864
      render: shell
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the issue(s)"
      description: |
        Provide a summary of the issue(s). This description applies to all instances if reporting many.
        **Optional:** You can upload an image by dragging and dropping it into the issue description or by using the 'Attach files' feature below.
      placeholder: "E.g., these flowpaths are missing connections to the main river channel..."
    validations:
      required: false