# .github/ISSUE_TEMPLATE/03-reid-divide.yml

name: "Divides: Reid Divide"
description: "Report divide reidentification issues."
title: "[Hydrofabric] Divides <item-identifier> Reid Divide"
labels:
  - Hydrofabric-reid-divide
body:
  - type: markdown
    attributes:
      value: |
        The title should not be changed and will be automatically updated based on the Item Identifier.
        Thanks for reporting a hydrofabric issue!
        Please provide the required details below.
        All issues must be reported using reference fabric identifiers. If an issue originates in a refactored or NextGen hydrofabric, please trace it back to the reference fabric before submitting. Use the [Hydrofabric Viewer Map](https://hydrofabric.lynker-spatial.com/) for assistance.
  - type: dropdown
    id: hf-version
    attributes:
      label: "Hydrofabric Version"
      description: "Select the type of hydrofabric version."
      options:
        - v2.2
        - v2.3
    validations:
      required: true
  - type: dropdown
    id: report-mode
    attributes:
      label: "Report Mode"
      description: "Select if you are reporting a single re-identification operation or multiple separate operations."
      options:
        - "Report a single reid operation"
        - "Report many reid operations (paste columns of data)"
    validations:
      required: true
  - type: textarea 
    id: vpu 
    attributes:
      label: "VPU(s)" 
      description: |
        The VPU(s) where the re-identification operation(s) occur (e.g., 01).
        If 'Report many reid operations' is selected, paste one VPU per line (copy and paste column as plain text without header), corresponding to each Current Item Identifier.
      placeholder: |
        01
        01
        02
      render: shell
    validations:
      required: true 
  - type: textarea 
    id: item-identifier 
    attributes:
      label: "Current Item Identifier(s)" 
      description: |
        The **current** divide id(s) to be re-identified (e.g., 620629).
        If 'Report many reid operations' is selected, paste one current identifier per line (copy and paste column as plain text without header).
      placeholder: |
        620629
        730510
        840220
      render: shell
    validations:
      required: true 
  - type: textarea 
    id: new-id 
    attributes:
      label: "New ID(s)" 
      description: |
        The **desired new** divide id(s) (e.g., 620630).
        If 'Report many reid operations' is selected, paste one new identifier per line (copy and paste column as plain text without header), corresponding to each Current Item Identifier.
      placeholder: |
        620630
        730511
        840221
      render: shell
    validations:
      required: true
  - type: textarea
    id: issue-description 
    attributes:
      label: "Describe the reid operations"
      description: |
        Provide a summary of why these re-identification operations are needed. This description applies to all operations if reporting many.
        **Optional:** You can upload an image by dragging and dropping it into this description box or by using the 'Attach files' feature below.
      placeholder: "E.g., these divides need to be reidentified due to a recent upstream merge..."
    validations:
      required: false