# .github/ISSUE_TEMPLATE/04-remove-flowpaths.yml

name: "Map Error: Remove Flowpaths"
description: "Report flowpaths that need to be removed."
title: "[Map Error] <item-identifier> Remove Flowpaths"
labels:
  - reid_divide-remove-flowpaths
body:
  - type: markdown
    attributes:
      value: |
        The title should not be changed and will be automatically updated based on the Item Identifier.
        Thanks for reporting a map item error!
        Please provide the required details below.
        Use this map to identify the item: [Map](https://spatial.dev.water.noaa.gov/view/hydrofabric).
  - type: input
    id: item-identifier
    attributes:
      label: "Item Identifier"
      description: "The flowpath id to remove (e.g., wb-620629)."
      placeholder: "wb-620629"
    validations:
      required: true
  - type: input
    id: vpu
    attributes:
      label: "VPU"
      description: "The VPU where the issue occurs (e.g., 01)."
      placeholder: "01"
    validations:
      required: true
  - type: dropdown
    id: hf-version
    attributes:
      label: "Hydrofabric Version"
      description: "Select the type of hydrofabric version."
      options:
        - v2.2
        - other
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the issue"
      description: "Provide a summary of the issue. **Optional:** You can upload an image by dragging and dropping it into the issue description or by using the 'Attach files' feature below."
      placeholder: "E.g., this flowpath should be removed..."
    validations:
      required: false