# .github/ISSUE_TEMPLATE/05-union-divides.yml

name: "Divides: Union Divides"
description: "Report divides that need to be unioned."
title: "[Hydrofabric] Divides <item-identifier> Union Divides"
labels:
  - Hydrofabric-union-divides
body:
  - type: markdown
    attributes:
      value: |
        The title should not be changed and will be automatically updated based on the Item Identifier.
        Thanks for reporting a hydrofabric issue!
        Please provide the required details below.
        **Important Note: the new divide identifier needs to be the most downstream of the IDs to merge.**
        All issues must be reported using reference fabric identifiers. If an issue originates in a refactored or NextGen hydrofabric, please trace it back to the reference fabric before submitting. Use the [Hydrofabric Viewer Map](https://hydrofabric.lynker-spatial.com/) for assistance.
  - type: dropdown
    id: hf-version
    attributes:
      label: "Hydrofabric Version"
      description: "Select the type of hydrofabric version."
      options:
        - v2.2
        - v2.3
    validations:
      required: true
  - type: dropdown
    id: report-mode
    attributes:
      label: "Report Mode"
      description: "Select if you are reporting a single union operation or multiple separate union operations."
      options:
        - "Report a single union operation"
        - "Report many union operations (paste columns of data)"
    validations:
      required: true
  - type: textarea 
    id: vpu 
    attributes:
      label: "VPU(s)" 
      description: |
        The VPU(s) where the union operation(s) occur (e.g., 01).
        If 'Report many union operations' is selected, paste one VPU per line, corresponding to each new Item Identifier.
      placeholder: |
        01
        01
        02
      render: shell
    validations:
      required: true
  - type: textarea 
    id: item-identifier 
    attributes:
      label: "New Item Identifier(s)" 
      description: |
        The **new** divide id(s) after unioning (e.g., 620629). One per line if reporting many operations.
      placeholder: |
        620629
        730510
        840220
      render: shell
    validations:
      required: true
  - type: textarea 
    id: id-to-merge 
    attributes:
      label: "List(s) of IDs to Merge" 
      description: |
        For each new item identifier (each line above), provide the corresponding list of existing divide IDs to be unioned.
        **Each line here should be a comma-separated list of IDs** (e.g., '620629,620630,620631').
        Ensure the number of lines here matches the number of 'New Item Identifier(s)'.
      placeholder: |
        620629,620630,620631
        730510,730500
        840220,840200,840190
      render: shell
    validations:
      required: true 
  - type: textarea
    id: issue-description 
    attributes:
      label: "Describe the union operations"
      description: |
        Provide a summary of why these union operations are needed. This description applies to all operations if reporting many.
        **Optional:** You can upload an image by dragging and dropping it into this description box or by using the 'Attach files' feature below.
      placeholder: "E.g., these divides represent a single catchment area and need to be unioned..."
    validations:
      required: false