# .github/ISSUE_TEMPLATE/06-hydrolocations-additions.yml

name: "Hydrolocations: Hydrolocations Additions"
description: "Propose new hydrolocations (Points of Interest) to be added."
title: "[Hydrofabric] Hydrolocations <hl_link> New Addition" 
labels:
  - Hydrofabric-hydrolocation-additions
body:
  - type: markdown
    attributes:
      value: |
        The title will be automatically updated based on the "HL Link (Internal ID)" you provide below.
        Use this template to propose **new** hydrolocations to be added to the hydrofabric.
        Please provide the required details below.
        Use this map to extract extra information if needed: [Map](https://staging.lynker-spatial.com/hfview.html).
  - type: dropdown
    id: hf-version
    attributes:
      label: "Hydrofabric Version"
      description: "Select the hydrofabric version this addition applies to."
      options:
        - v2.2
        - v2.3
    validations:
      required: true
  - type: dropdown
    id: report-mode
    attributes:
      label: "Report Mode"
      description: "Select if you are proposing a single new hydrolocation or multiple."
      options:
        - "Report a single new hydrolocation"
        - "Report many new hydrolocations (paste columns of data)"
    validations:
      required: true
  - type: textarea
    id: vpu
    attributes:
      label: "VPU(s)"
      description: |
        The VPU(s) where the new hydrolocation(s) should be located (e.g., 01).
        If 'Report many...', paste one VPU per line.
      placeholder: |
        01
        02
      render: shell
    validations:
      required: true
  - type: textarea
    id: hl-reference
    attributes:
      label: "HL Reference(s)"
      description: |
        The reference source for the hydrolocation (e.g., usgs-gage, state-agency-id).
        One per line if reporting many.
      placeholder: |
        usgs-gage
        lid
      render: shell
    validations:
      required: true
  - type: textarea
    id: hl-link 
    attributes:
      label: "HL Link (Internal ID / Unique Identifier)(s)"
      description: |
        The unique internal ID or link for this new hydrolocation (e.g., a specific gauge number, a unique project ID). This will be used in the issue title.
        One per line if reporting many.
      placeholder: |
        07300000
        MATM1
      render: shell
    validations:
      required: true
  - type: textarea
    id: hl-source
    attributes:
      label: "HL Source (Optional)"
      description: |
        The source or originator of this hydrolocation data (e.g., an organization name, project name).
        If left blank, your GitHub username will be used.
        One per line if reporting many
      placeholder: |
        My Organization Name
        NWS
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Please provide the coordinates and EPSG code for the new hydrolocation(s).
        **Example:**
        - Latitude: 37.7749
        - Longitude: -122.4194
        - EPSG Code: 4326 (WGS84)
  - type: textarea
    id: latitude
    attributes:
      label: "Latitude(s)"
      description: |
        The latitude coordinate(s) for the new POI(s).
        One per line if reporting many.
      placeholder: |
        37.7749
        36.1699
      render: shell
    validations:
      required: true
  - type: textarea
    id: longitude
    attributes:
      label: "Longitude(s)"
      description: |
        The longitude coordinate(s) for the new POI(s).
        One per line if reporting many.
      placeholder: |
        -122.4194
        -115.1398
      render: shell
    validations:
      required: true
  - type: textarea
    id: epsg-code
    attributes:
      label: "EPSG Code(s)"
      description: |
        The numerical EPSG code(s) for the new coordinates.
        One per line if reporting many, or single on first line if all same.
      placeholder: |
        4326
        5070
      render: shell
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the new hydrolocation(s) / Additional Details"
      description: |
        Provide any additional details, justification, or context for adding these hydrolocations. This description applies to all instances if reporting many.
        **Optional:** You can upload an image by dragging and dropping it.
      placeholder: "E.g., These are newly installed monitoring stations..."
    validations:
      required: false